#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.certificates.useCertManager:

#@ certgen_sa = overlay.subset({"kind":"ServiceAccount", "metadata":{"name":"contour-certgen"}})
#@ certgen_rb = overlay.subset({"kind":"RoleBinding", "roleRef":{"name":"contour-certgen"}})
#@ certgen_role = overlay.subset({"kind":"Role", "metadata":{"name":"contour-certgen"}})
#@ certgen_job = overlay.subset({"kind":"Job"})

#@overlay/match by=overlay.or_op(certgen_sa, certgen_rb, certgen_role, certgen_job), expects=4
#@overlay.remove
---

#@ else:

#@overlay/match by=overlay.subset({"kind":"Job"}),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: "fallback-on-replace"

#@ end
