#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/contour.star", "get_envoy_service_type", "get_envoy_service_annotations", "get_envoy_service_external_traffic_policy")

#@ node_ports_enabled = get_envoy_service_type() == "NodePort" or get_envoy_service_type() == "LoadBalancer"

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"name":"envoy"}})
---
metadata:
  #@overlay/replace
  annotations: #@ get_envoy_service_annotations()
spec:
  type: #@ get_envoy_service_type()

  ports:
  #@overlay/match by=overlay.subset({"name":"http"})
  -
    #@ if/end node_ports_enabled and data.values.envoy.service.nodePorts.http:
    #@overlay/match missing_ok=True
    nodePort: #@ data.values.envoy.service.nodePorts.http
    targetPort: http
  #@overlay/match by=overlay.subset({"name":"https"})
  -
    #@ if/end node_ports_enabled and data.values.envoy.service.nodePorts.https:
    #@overlay/match missing_ok=True
    nodePort: #@ data.values.envoy.service.nodePorts.https
    targetPort: https

  #@ if/end data.values.envoy.service.loadBalancerIP and get_envoy_service_type() == "LoadBalancer":
  #@overlay/match missing_ok=True
  loadBalancerIP: #@ data.values.envoy.service.loadBalancerIP

  #@ if get_envoy_service_type() == "NodePort" or get_envoy_service_type() == "LoadBalancer":
  externalTrafficPolicy: #@ get_envoy_service_external_traffic_policy()
  #@ else:
  #@overlay/remove
  externalTrafficPolicy: Local
  #@ end
