#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ node_ports_enabled = data.values.envoy.service.type == "NodePort" or data.values.envoy.service.type == "LoadBalancer"

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"name":"envoy"}})
---
metadata:
  #@overlay/replace
  annotations: #@ data.values.envoy.service.annotations
spec:
  type: #@ data.values.envoy.service.type

  ports:
  #@overlay/match by=overlay.subset({"name":"http"})
  -
    #@ if/end node_ports_enabled and data.values.envoy.service.nodePorts.http:
    #@overlay/match missing_ok=True
    nodePort: #@ data.values.envoy.service.nodePorts.http
    targetPort: http
  #@overlay/match by=overlay.subset({"name":"https"})
  -
    #@ if/end node_ports_enabled and data.values.envoy.service.nodePorts.https:
    #@overlay/match missing_ok=True
    nodePort: #@ data.values.envoy.service.nodePorts.https
    targetPort: https

  #@ if/end data.values.envoy.service.loadBalancerIP and data.values.envoy.service.type == "LoadBalancer":
  #@overlay/match missing_ok=True
  loadBalancerIP: #@ data.values.envoy.service.loadBalancerIP

  #@overlay/match missing_ok=True
  externalTrafficPolicy: #@ data.values.envoy.service.externalTrafficPolicy
