#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Namespace", "metadata":{"name":"projectcontour"}}), expects=1
---
metadata:
  name: #@ data.values.namespace

#@overlay/match by=overlay.subset({"metadata":{"namespace":"projectcontour"}}), expects="12+"
---
metadata:
  namespace: #@ data.values.namespace

#@ cluster_role_binding = overlay.subset({"kind":"ClusterRoleBinding"})
#@ role_binding = overlay.subset({"kind":"RoleBinding"})

#@overlay/match by=overlay.or_op(cluster_role_binding, role_binding), expects="2+"
---
subjects:
#@overlay/match by=overlay.subset({"namespace":"projectcontour"})
- kind: ServiceAccount
  namespace: #@ data.values.namespace
