#@ load("@ytt:data", "data")

---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.50.0

#! Wait rules specify how to wait for resources that kapp does not wait for by default.
#! See more about the wait rules: https://carvel.dev/kapp/docs/latest/config/#waitrules.
waitRules:

- supportsObservedGeneration: false
  conditionMatchers:
  - type: Ready
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: cert-manager.io/v1, kind: Certificate}
  - apiVersionKindMatcher: {apiVersion: cert-manager.io/v1, kind: Issuer}

#! Specify which fields should be removed before diff-ing against last applied resource.
#! See more: https://carvel.dev/kapp/docs/latest/config/#diffagainstlastappliedfieldexclusionrules
diffAgainstLastAppliedFieldExclusionRules:

#! Each cloud provider will add its own custom annotations to the Envoy Service in order
#! to configure the associated load balancer. We want to keep those annotations between
#! upgrades, so we exclude them from the diff to prevent them being overwritten.
- path: [metadata, annotations]
  type: copy
  sources: [existing]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Service
      namespace: #@ data.values.namespace
      name: envoy

#! Bind change groups to resources matched by resource matchers.
#! See more: https://carvel.dev/kapp/docs/v0.62.x/config/#changegroupbindings
changeGroupBindings:

- name: change-groups.kapp.k14s.io/envoy-daemonset
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: DaemonSet
      namespace: #@ data.values.namespace
      name: envoy

- name: change-groups.kapp.k14s.io/envoy-deployment
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Deployment
      namespace: #@ data.values.namespace
      name: envoy


#! Bind change groups to resources matched by resource matchers.
#! See more: https://carvel.dev/kapp/docs/v0.62.x/config/#changerulebindings
changeRuleBindings:

#! Ensure zero-downtime when switching the Envoy workload
#! from a DaemonSet to Deployment.
- rules:
  - "upsert before deleting change-groups.kapp.k14s.io/envoy-daemonset"
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Deployment
      namespace: #@ data.values.namespace
      name: envoy

#! Ensure zero-downtime when switching the Envoy workload
#! from a Deployment to DaemonSet.
- rules:
  - "upsert before deleting change-groups.kapp.k14s.io/envoy-deployment"
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: DaemonSet
      namespace: #@ data.values.namespace
      name: envoy
